{{- if .Values.appmetier1.include -}}

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: app-metier1
  name: app-metier1
  namespace: app-metier1  
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: app-metier1
    weight: 100
  wildcardPolicy: None

{{- end }}