{{- if .Values.appmetier1.include -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app-metier2
  labels:
    application: app-metier2
  name: app-metier2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      deploymentconfig: app-metier2
  template:
    metadata:
      labels:
        app: app-metier2
        deploymentconfig: app-metier2
      name: app-metier2
    spec:
      containers:
      - name: apache
        image: registry.access.redhat.com/ubi8/httpd-24:1-226
        #imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html
          name: app-metier2-configmap
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: app-metier2-configmap
        configMap:
          defaultMode: 438
          name: app-metier2-configmap

{{- end }}