{{- if .Values.appmetier1.include -}}

apiVersion: v1
kind: Namespace
metadata:
  namespace: app-metier2
  annotations:
    openshift.io/display-name: {{ .Values.cluster.name }}
    cluster.open-cluster-management.io/managedCluster: {{ .Values.cluster.name }}
    kubernetes.io/metadata.name: {{ .Values.cluster.name }}
    helm.sh/hook-weight: "350"
  name: app-metier2

{{- end }}