{{- if .Values.appmetier1.include -}}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-metier2
  name: app-metier2
  namespace: app-metier2  
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-metier2
    deploymentconfig: app-metier2
  sessionAffinity: None
  type: ClusterIP

{{- end }}